/**
 * Centralized Error Codes for UniPlatform API
 */
const ERROR_CODES = {
  AUTH: {
    AUTH_INVALID: 'AUTH_INVALID',
    AUTH_LOCKED: 'AUTH_LOCKED',
    AUTH_MISSING: 'AUTH_MISSING',
    AUTH_ERROR: 'AUTH_ERROR',
    USER_EXISTS: 'USER_EXISTS',
    USER_NOT_FOUND: 'USER_NOT_FOUND',
  },
  VALIDATION: {
    VALIDATION_ERROR: 'VALIDATION_ERROR',
  },
  USER: {
    PASS_INVALID: 'PASS_INVALID',
    USER_NOT_FOUND: 'USER_NOT_FOUND',
  },
  WORKSPACE: {
    WKS_NOT_FOUND: 'WKS_NOT_FOUND',
  },
  FILE: {
    FILE_MISSING: 'FILE_MISSING',
    FILE_NOT_FOUND: 'FILE_NOT_FOUND',
  },
  SYSTEM: {
    INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
    BAD_REQUEST: 'BAD_REQUEST',
    ERROR: 'ERROR',
  },
};

module.exports = ERROR_CODES;
